### PR TITLE
Update to 'upTime' validator field to include block uptime

### PR DESCRIPTION
**Pull request by Matthews3301**
Currently, validatorDetails response data includes `upTime` field which doesn't actually show uptime of a validator. Instead, it returns getOracleUptime, i.e. a relative amount of missed oracle blocks.

It would make more sense to return a number which indicates how many oracle votes as well as block commits the validator has missed.

This pull request updates `upTime` to include block uptime and oracle uptime in one number. E.g. if the block uptime is 0.8 and oracle uptime is 0.9 then `upTime` will be `0.72`. If both are 1 then `upTime` remains `1`.

### CODE REVIEW

**Comment by hanjukim** [comment]
How do you think of this? @terra-money/dev-releations

**Comment by Jared-Warn** [comment]
The combined metric is also misleading. We could provide both uptimes separately. They have different reward bands, and different implications. A combined metric could then be determined by whoever queries the oracle and block uptimes.
However, providing a combined metric as the only option on such a base level would be misleading.

**Comment by Matthews3301** [comment]
@Jared-Warn I changed it to provide `upTimeOracle` and `upTimeBlock` separately. Is this preferable?

**Comment by Jared-Warn** [comment]
The 2 uptimes proposed are easy to understand, and add value for validators. This allows them to pinpoint operational issues with more accuracy. IE is the oracle malfunctioning, or is the whole machine down.

I say, let's do it.

**Comment by hanjukim** [comment]
Validator uptime calculation will be provided from another service. (api.terra.dev). Closing this issue.

**Pull request closed without merging**
